# Generated by Django 4.2 on 2024-04-04 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activate_token",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
