# Generated by Django 4.2 on 2024-04-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_activate_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
    ]
