# Generated by Django 4.2 on 2024-04-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blogpost_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="creation_date",
            field=models.DateField(
                blank=True,
                default="2024-04-12",
                null=True,
                verbose_name="дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="publication_sign",
            field=models.BooleanField(default=False, verbose_name="опубликовано"),
        ),
    ]
